environment:
  matrix:
     - GENERATOR: "Visual Studio 14 2015 Win64"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 14 2015 Win64"
       CONFIG: Release

install:
  - set QTDIR=C:\Qt\5.7\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - python build_system/appveyor.helper.py

artifacts:
  - name: Installer
    path: 'OpenVideoDiary-*.exe'

matrix:
  fast_finish: true
