environment:
  matrix:
     - GENERATOR: "Visual Studio 14 2015 Win64"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 14 2015 Win64"
       CONFIG: Release

install:
  - set QTDIR=C:\Qt\5.11.1\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - python build_system/appveyor.helper.py

artifacts:
  - name: Installer
    path: 'OpenVideoDiary-*.exe'
  - name: Binary
    path: 'src/Debug/OpenVideoDiary.exe'

matrix:
  fast_finish: true

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: jm9elO7x1o31K66/sTr4Msp8Ufl5H00zmOztY+d8vKn+36WSAnzCnHirgRD4/Byc
  artifact: /OpenVideoDiary-.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
